- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/empty/model/human1/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: BIDIRECTIONAL

- ros_topic_name: "/tf"
  gz_topic_name: "/model/human1/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: BIDIRECTIONAL