# Default initial positions for human_support's ros2_control fake system

initial_positions:
  jC1Head_rotx: 0
  jC1Head_roty: 0
  jC7LeftShoulder_rotx: 0
  jC7RightShoulder_rotx: 0
  jL5S1_rotx: 0
  jL5S1_roty: 0
  jLeftAnkle_rotx: 0
  jLeftAnkle_roty: 0
  jLeftAnkle_rotz: 0
  jLeftBallFoot_roty: 0
  jLeftElbow_roty: 0
  jLeftElbow_rotz: 0
  jLeftHip_rotx: 0
  jLeftHip_roty: 0
  jLeftHip_rotz: 0
  jLeftKnee_roty: 0
  jLeftKnee_rotz: 0
  jLeftShoulder_rotx: 0
  jLeftShoulder_roty: 0
  jLeftShoulder_rotz: 0
  jLeftWrist_rotx: 0
  jLeftWrist_rotz: 0
  jRightAnkle_rotx: 0
  jRightAnkle_roty: 0
  jRightAnkle_rotz: 0
  jRightBallFoot_roty: 0
  jRightElbow_roty: 0
  jRightElbow_rotz: 0
  jRightHip_rotx: 0
  jRightHip_roty: 0
  jRightHip_rotz: 0
  jRightKnee_roty: 0
  jRightKnee_rotz: 0
  jRightShoulder_rotx: 0
  jRightShoulder_roty: 0
  jRightShoulder_rotz: 0
  jRightWrist_rotx: 0
  jRightWrist_rotz: 0
  jT1C7_rotx: 0
  jT1C7_roty: 0
  jT1C7_rotz: 0
  jT9T8_rotx: 0
  jT9T8_roty: 0
  jT9T8_rotz: 0
  link1_link2_joint: 0
  link2_link3_joint: 0
  link3_link4_joint: 0