# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    # - support_arm_controller
    # - whole_body_controller
    - support_whole_body_controller

  # support_arm_controller:
  #   type: FollowJointTrajectory
  #   joints:
  #     - link1_link2_joint
  #     - link2_link3_joint
  #     - link3_link4_joint
  #   action_ns: follow_joint_trajectory
  #   default: true
  # whole_body_controller:
  #   type: FollowJointTrajectory
  #   joints:
  #     - jL5S1_rotx
  #     - jL5S1_roty
  #     - jT9T8_rotx
  #     - jT9T8_roty
  #     - jT9T8_rotz
  #     - jC7LeftShoulder_rotx
  #     - jLeftShoulder_rotx
  #     - jLeftShoulder_roty
  #     - jLeftShoulder_rotz
  #     - jLeftElbow_roty
  #     - jLeftElbow_rotz
  #     - jLeftWrist_rotx
  #     - jLeftWrist_rotz
  #     - jC7RightShoulder_rotx
  #     - jRightShoulder_rotx
  #     - jRightShoulder_roty
  #     - jRightShoulder_rotz
  #     - jRightElbow_roty
  #     - jRightElbow_rotz
  #     - jRightWrist_rotx
  #     - jRightWrist_rotz
  #     - jT1C7_rotx
  #     - jT1C7_roty
  #     - jT1C7_rotz
  #     - jC1Head_rotx
  #     - jC1Head_roty
  #     - jLeftHip_rotx
  #     - jLeftHip_roty
  #     - jLeftHip_rotz
  #     - jLeftKnee_roty
  #     - jLeftKnee_rotz
  #     - jLeftAnkle_rotx
  #     - jLeftAnkle_roty
  #     - jLeftAnkle_rotz
  #     - jLeftBallFoot_roty
  #     - jRightHip_rotx
  #     - jRightHip_roty
  #     - jRightHip_rotz
  #     - jRightKnee_roty
  #     - jRightKnee_rotz
  #     - jRightAnkle_rotx
  #     - jRightAnkle_roty
  #     - jRightAnkle_rotz
  #     - jRightBallFoot_roty
  #   action_ns: follow_joint_trajectory
  #   default: true
  support_whole_body_controller:
    type: FollowJointTrajectory
    joints:
      - link1_link2_joint
      - link2_link3_joint
      - link3_link4_joint
      - jL5S1_rotx
      - jL5S1_roty
      - jT9T8_rotx
      - jT9T8_roty
      - jT9T8_rotz
      - jC7LeftShoulder_rotx
      - jLeftShoulder_rotx
      - jLeftShoulder_roty
      - jLeftShoulder_rotz
      - jLeftElbow_roty
      - jLeftElbow_rotz
      - jLeftWrist_rotx
      - jLeftWrist_rotz
      - jC7RightShoulder_rotx
      - jRightShoulder_rotx
      - jRightShoulder_roty
      - jRightShoulder_rotz
      - jRightElbow_roty
      - jRightElbow_rotz
      - jRightWrist_rotx
      - jRightWrist_rotz
      - jT1C7_rotx
      - jT1C7_roty
      - jT1C7_rotz
      - jC1Head_rotx
      - jC1Head_roty
      - jLeftHip_rotx
      - jLeftHip_roty
      - jLeftHip_rotz
      - jLeftKnee_roty
      - jLeftKnee_rotz
      - jLeftAnkle_rotx
      - jLeftAnkle_roty
      - jLeftAnkle_rotz
      - jLeftBallFoot_roty
      - jRightHip_rotx
      - jRightHip_roty
      - jRightHip_rotz
      - jRightKnee_roty
      - jRightKnee_rotz
      - jRightAnkle_rotx
      - jRightAnkle_roty
      - jRightAnkle_rotz
      - jRightBallFoot_roty
    action_ns: follow_joint_trajectory
    default: true