# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    # support_arm_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController


    # whole_body_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController


    support_whole_body_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# support_arm_controller:
#   ros__parameters:
#     joints:
#       - link1_link2_joint
#       - link2_link3_joint
#       - link3_link4_joint
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
# whole_body_controller:
#   ros__parameters:
#     joints:
#       - jL5S1_rotx
#       - jL5S1_roty
#       - jT9T8_rotx
#       - jT9T8_roty
#       - jT9T8_rotz
#       - jC7LeftShoulder_rotx
#       - jLeftShoulder_rotx
#       - jLeftShoulder_roty
#       - jLeftShoulder_rotz
#       - jLeftElbow_roty
#       - jLeftElbow_rotz
#       - jLeftWrist_rotx
#       - jLeftWrist_rotz
#       - jC7RightShoulder_rotx
#       - jRightShoulder_rotx
#       - jRightShoulder_roty
#       - jRightShoulder_rotz
#       - jRightElbow_roty
#       - jRightElbow_rotz
#       - jRightWrist_rotx
#       - jRightWrist_rotz
#       - jT1C7_rotx
#       - jT1C7_roty
#       - jT1C7_rotz
#       - jC1Head_rotx
#       - jC1Head_roty
#       - jLeftHip_rotx
#       - jLeftHip_roty
#       - jLeftHip_rotz
#       - jLeftKnee_roty
#       - jLeftKnee_rotz
#       - jLeftAnkle_rotx
#       - jLeftAnkle_roty
#       - jLeftAnkle_rotz
#       - jLeftBallFoot_roty
#       - jRightHip_rotx
#       - jRightHip_roty
#       - jRightHip_rotz
#       - jRightKnee_roty
#       - jRightKnee_rotz
#       - jRightAnkle_rotx
#       - jRightAnkle_roty
#       - jRightAnkle_rotz
#       - jRightBallFoot_roty
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
support_whole_body_controller:
  ros__parameters:
    joints:
      - link1_link2_joint
      - link2_link3_joint
      - link3_link4_joint
      - jL5S1_rotx
      - jL5S1_roty
      - jT9T8_rotx
      - jT9T8_roty
      - jT9T8_rotz
      - jC7LeftShoulder_rotx
      - jLeftShoulder_rotx
      - jLeftShoulder_roty
      - jLeftShoulder_rotz
      - jLeftElbow_roty
      - jLeftElbow_rotz
      - jLeftWrist_rotx
      - jLeftWrist_rotz
      - jC7RightShoulder_rotx
      - jRightShoulder_rotx
      - jRightShoulder_roty
      - jRightShoulder_rotz
      - jRightElbow_roty
      - jRightElbow_rotz
      - jRightWrist_rotx
      - jRightWrist_rotz
      - jT1C7_rotx
      - jT1C7_roty
      - jT1C7_rotz
      - jC1Head_rotx
      - jC1Head_roty
      - jLeftHip_rotx
      - jLeftHip_roty
      - jLeftHip_rotz
      - jLeftKnee_roty
      - jLeftKnee_rotz
      - jLeftAnkle_rotx
      - jLeftAnkle_roty
      - jLeftAnkle_rotz
      - jLeftBallFoot_roty
      - jRightHip_rotx
      - jRightHip_roty
      - jRightHip_rotz
      - jRightKnee_roty
      - jRightKnee_rotz
      - jRightAnkle_rotx
      - jRightAnkle_roty
      - jRightAnkle_rotz
      - jRightBallFoot_roty
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity