<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="arm_base_length" value="0.1"/>
    <xacro:property name="arm_base_width" value="0.1"/>
    <xacro:property name="arm_base_height" value="0.02"/>
    <xacro:property name="arm_radius" value="0.02"/>
    <xacro:property name="arm_length" value="0.25"/>

    <!-- length link1 should be at least the length of foot collision box (0.2584 meters) -->
    <xacro:property name="link1_length" value="0.5"/>
    <!-- revolute arm links are small to keep the movement gathered -->
    <xacro:property name="revolute_arm_length" value="0.05"/>
    <!-- twist arm length is the rest of the length to get to 1 meter from end of link 1 -->
    <xacro:property name="twist_arm_length" value="${1-(revolute_arm_length*2)}"/>

    <link name="arm_base_link">
        <!-- <visual>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${arm_base_height/2}" rpy="0.0 0.0 0.0"/>
            <material name="orange"/>
        </visual>
        <collision>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${arm_base_height/2}" rpy="0.0 0.0 0.0"/>
        </collision> -->
        <xacro:box_inertia m="0.5" l="${arm_base_length}" w="${arm_base_width}" h="${arm_base_height}"
                           xyz="0.0 0.0 ${arm_base_height/2.0}" rpy="0.0 0.0 0.0" />
    </link>

    <link name="link1">
        <!-- <visual>
            <geometry>
                <cylinder radius="${arm_radius}" length="${link1_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${link1_length/2}" rpy="0.0 0.0 0.0"/>
            <material name="yellow"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${arm_radius}" length="${link1_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${link1_length/2}" rpy="0.0 0.0 0.0"/>
        </collision> -->
        <xacro:cylinder_inertia m="0.3" r="${arm_radius}" h="${link1_length}"
                                xyz="0.0 0.0 ${link1_length/2}" rpy="0.0 0.0 0.0" />
    </link>

    <link name="link2">
        <!-- <visual> 
            <geometry>
                <cylinder radius="${arm_radius}" length="${revolute_arm_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${revolute_arm_length/2}" rpy="0.0 0.0 0.0"/>
            <material name="orange"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${arm_radius}" length="${revolute_arm_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${revolute_arm_length/2}" rpy="0.0 0.0 0.0"/>
        </collision> -->
        <xacro:cylinder_inertia m="0.3" r="${arm_radius}" h="${revolute_arm_length}"
                                xyz="0.0 0.0 ${revolute_arm_length/2}" rpy="0.0 0.0 0.0" />
    </link>

    <link name="link3">
        <!-- <visual>
            <geometry>
                <cylinder radius="${arm_radius}" length="${revolute_arm_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${revolute_arm_length/2}" rpy="0.0 0.0 0.0"/>
            <material name="yellow"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${arm_radius}" length="${revolute_arm_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${revolute_arm_length/2}" rpy="0.0 0.0 0.0"/>
        </collision> -->
        <xacro:cylinder_inertia m="0.3" r="${arm_radius}" h="${revolute_arm_length}"
                                xyz="0.0 0.0 ${revolute_arm_length/2}" rpy="0.0 0.0 0.0" />
    </link>

    <link name="link4">
        <!-- <visual>
            <geometry>
                <cylinder radius="${arm_radius}" length="${twist_arm_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${twist_arm_length/2}" rpy="0.0 0.0 0.0"/>
            <material name="orange"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${arm_radius}" length="${twist_arm_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${twist_arm_length/2}" rpy="0.0 0.0 0.0"/>
        </collision> -->
        <xacro:cylinder_inertia m="0.3" r="${arm_radius}" h="${twist_arm_length}"
                                xyz="0.0 0.0 ${twist_arm_length/2}" rpy="0.0 0.0 0.0" />
    </link>

    <!-- Fixed joint to slightly raise humanoid before movement -->
    <joint name="base_link1_joint" type="fixed">
        <parent link="arm_base_link"/>
        <child link="link1"/>
        <origin xyz="0 0 ${arm_base_height}" rpy="0 0 0"/>
    </joint>

    <joint name="link1_link2_joint" type="revolute">
        <parent link="link1"/>
        <child link="link2"/>
        <axis xyz="1 0 0"/>
        <limit lower="${-pi/2}" upper="${pi/2}" velocity="100.0" effort="1000.0"/>
        <origin xyz="0 0 ${link1_length}" rpy="0 0 0"/>
        <!-- <dynamics damping="1.0" friction="1.0"/> -->
    </joint>

    <joint name="link2_link3_joint" type="revolute">
        <parent link="link2"/>
        <child link="link3"/>
        <axis xyz="0 1 0"/>
        <limit lower="${-pi/2}" upper="${pi/2}" velocity="100.0" effort="1000.0"/>
        <origin xyz="0 0 ${revolute_arm_length}" rpy="0 0 0"/>
        <!-- <dynamics damping="1.0" friction="1.0"/> -->
    </joint>

    <joint name="link3_link4_joint" type="continuous">
        <parent link="link3"/>
        <child link="link4"/>
        <axis xyz="0 0 1"/>
        <limit lower="${-pi/2}" upper="${pi/2}" velocity="100.0" effort="1000.0"/>
        <origin xyz="0 0 ${revolute_arm_length}" rpy="0 0 0"/>
        <!-- <dynamics damping="1.0" friction="1.0"/> -->
    </joint>

</robot>